name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      id-token: write
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
      - name: Fetch tags
        run: git fetch --tags
      - name: setup-pnpm
        uses: pnpm/action-setup@v4
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: install
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm run build
      - name: release
        run: pnpm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
