name: lint

on:
  pull_request:
    types: [assigned, edited, opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-pnpm
        uses: pnpm/action-setup@v4
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: install
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm run lint
